#include "modules/register_module_types.h"

void initialize_godot_vram_bridge_module(ModuleInitializationLevel p_level);
void uninitialize_godot_vram_bridge_module(ModuleInitializationLevel p_level);
